name: Cypress Tests

on: [push]

jobs:
  Checkout-code:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.3.0 # use the explicit version number
        with:
          build: npx cypress run --env email=julio.franco9111@gmail.com,password=1a83a92f8ceb7
          start: npm run test